services:
  - docker

before_install:
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

install:
  - make docker-build
  - sleep 10
  - make docker-up
  - sleep 10
  - docker ps -a

script:
  - make docker-test
