version: '3.4'

services:

  template:
    build:
      context: ./
      args:
        - application=template
        - friendly="TEMPLATE API"
        - build_hash=${HASH:-localbuild_hashmissing}
        - build_user=${BUILD_USER:-$USER}
        - build_branch=${BRANCH:-nobranch}
        - build_number=${BUILD_NUMBER:-1.0.0}
        - build_group=${BUILD_GROUP:-nogroupspecified}
    image: template/template-api:${BUILD_NUMBER:-1.0.0}
    container_name: template
    volumes:
      - ./application:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: "nodemon --watch 'src/**/*.ts' --exec 'ts-node' src/index.ts"
